"""init

Revision ID: 428830fbbe97
Revises: 
Create Date: 2022-04-18 21:40:53.427185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428830fbbe97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
